name: Deploy Blog

on:
  push:
    branches: develop
    # Contentful에서 제공하는 Webhook 기능을 통해 게시글과 관련된 특정 이벤트가 발생할 때마다 매번 배포 워크플로우를 실행시켜 자동으로 블로그 글을 갱신 기능 추가
  repository_dispatch:
    types: [publish-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 원하는 Github Secrets을 불러와 env 파일을 생성해줍니다.
      - name: Generate env file
        run: |
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

      - name: Deploy gatsby
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOYMENT_ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --verbose #빌드 동작 확인을 위한 작업
